[package]
name = "glacex"
version = "0.1.1"
edition = "2024"
rust-version = "1.85"
description = "GPU-accelerated UI library built from scratch in Rust"
readme = "README.md"
license = "MIT"
keywords = ["gui", "wgpu", "ui", "graphics"]
categories = ["gui", "graphics"]
exclude = ["screenshots/*"]

[dependencies]
arboard = "3.6.1"
bytemuck = { version = "1.25.2", features = ["derive"] }
env_logger = "0.11.11"
glyphon = "0.12.0"
pollster = "1.0.1"
taffy = "0.13.0"
wgpu = "30.0.0"
winit = "0.30.13"
